### ISSUE TITLE
项目在h5下报错

### ISSUE THREAD

**Issue by sansx** [psaren/taro-mbox#1]
项目在运行`npm run dev:h5`的时候报错了
小程序时可以正常编译的
我的版本是Taro v1.3.4
报错信息：
```
(node:5563) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'enableDll' in /Users/maitianer/Documents/test/taro-mbox
    at Object.<anonymous> (/Users/maitianer/Documents/test/taro-mbox/node_modules/_@tarojs_webpack-runner@1.2.26@@tarojs/webpack-runner/dist/index.js:108:25)
    at Generator.next (<anonymous>)
    at /Users/maitianer/Documents/test/taro-mbox/node_modules/_@tarojs_webpack-runner@1.2.26@@tarojs/webpack-runner/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/maitianer/Documents/test/taro-mbox/node_modules/_@tarojs_webpack-runner@1.2.26@@tarojs/webpack-runner/dist/index.js:3:12)
    at exports.default (/Users/maitianer/Documents/test/taro-mbox/node_modules/_@tarojs_webpack-runner@1.2.26@@tarojs/webpack-runner/dist/index.js:98:31)
    at Compiler.<anonymous> (/Users/maitianer/.npm-global/lib/node_modules/@tarojs/cli/dist/h5/index.js:153:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/maitianer/.npm-global/lib/node_modules/@tarojs/cli/dist/h5/index.js:4:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:5563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by psaren** [comment]
我试了一下把taro和taro-cli升级到当前最新版本(1.3.8)后
`npm run dev:h5`
就可以正常运行了

**Comment by sansx** [comment]
好的，感谢大佬  
这个问题是我自己太粗心了  
我最近刚学，尽管看了文档好几遍，还是感觉用taro走哪都是坑，蜜汁难受

**Comment by psaren** [comment]
遇到坑，可以先到taro的issue去搜一下，应该大部分坑都被人遇到过，很多解决方案啦！

**Comment by sansx** [comment]
恩，主要是我两周前提了两个bug的issue，但是到现在还在处理中  
所以不常去那里逛  
总之还是感谢大佬及时的解答
